### ISSUE TITLE
Update URLs to point to correct place

### ISSUE THREAD

**Issue by mkevenaar** [gep13-oss/PoshBot.Soon#6]

**Comment by mkevenaar** [comment]
The current release notes point to https://raw.githubusercontent.com/gep13/PoshBot.Soon/develop/CHANGELOG.md and it does not exist.

**Comment by gep13** [comment]
@mkevenaar I am not a fan of duplicating information if we can avoid it.  In this case, I think we should change the URL to be:

https://github.com/gep13-oss/PoshBot.Soon/releases

Thoughts?

**Comment by mkevenaar** [comment]
Yip I agree. I was just following what was already there

**Comment by AdmiringWorm** [comment]
@gep13 @mkevenaar if you can, maybe point the release notes url directly to the exact release that was built?

**Comment by mkevenaar** [comment]
@AdmiringWorm That would mean that we need to change the ReleaseNotes URL on every release. I think pointing to the releases page is perfectly acceptable.

**Comment by mkevenaar** [comment]
Besides ReleaseNotes URL also the following URLs have been fixed:
* ProjectUri
* LicenseUri

**Comment by mkevenaar** [comment]
This is implemented here: https://github.com/gep13-oss/PoshBot.Soon/commit/d4a9a0561203bb78870dcafa8f4ab70cc397309a
